const buttonPlay = document.querySelector('.play')
const buttonPause = document.querySelector('.pause')
const buttonStop = document.querySelector('.stop')
const buttonTimeUp = document.querySelector('.btn-up')
const buttonTimeDown = document.querySelector('.btn-down')